SELECT 
    ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST)/count(*),2),'km') AS AVERAGE_DISTANCE
FROM subway_distance
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC
;