SELECT FLAVOR FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) FROM
    (SELECT * FROM FIRST_HALF F
    UNION ALL
    SELECT * FROM JULY J)
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC)
WHERE rownum<=3;




