SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN USED_GOODS_BOARD UGB
ON UGU.USER_ID = UGB.WRITER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY user_id
HAVING SUM(PRICE)>=700000
ORDER BY total_sales
;