-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(date_of_birth, '%Y-%m-%d') DATE_OF_BIRTH  FROM MEMBER_PROFILE
WHERE SUBSTR(DATE_OF_BIRTH, 6)=3 and GENDER='W' and TLNO IS NOT NULL ORDER BY MEMBER_ID;